CREATE TABLE USER_INFO
(
  ID        SERIAL PRIMARY KEY,
  EMAIL     VARCHAR(256) NOT NULL UNIQUE,
  USERNAME  VARCHAR(256) NOT NULL UNIQUE,
  PASS_HASH VARCHAR(256) NOT NULL
);

CREATE TABLE DATASOURCE
(
  ID                   SERIAL PRIMARY KEY,
  DATASOURCE_SHOW_NAME VARCHAR(256) NOT NULL,
  CONNECTION_URL       VARCHAR(512) NOT NULL
);

CREATE TABLE REPORT
(
  ID            SERIAL PRIMARY KEY,
  REPORT_NAME   VARCHAR(256)                       NOT NULL,
  REPORT_DATA   TEXT                               NOT NULL,
  START_DATE    DATE                               NOT NULL,
  END_DATE      DATE,
  EXEC_TIME     TIME                               NOT NULL,
  PERIOD_MODE   VARCHAR(256)                       NOT NULL,
  DATASOURCE_ID INTEGER REFERENCES DATASOURCE (ID) NOT NULL,
  USER_ID       INTEGER REFERENCES USER_INFO (ID)  NOT NULL
);

CREATE TABLE REPORT_EXEC_DATA
(
  EXEC_TIME TIMESTAMP                      NOT NULL,
  REAL_TIME TIMESTAMP                      NOT NULL,
  EXEC_DATA TEXT                           NOT NULL,
  REPORT_ID INTEGER REFERENCES REPORT (ID) NOT NULL
);